import {
  LayoutDashboard,
  Users,
  Settings,
  MessageSquare,
  FileCheck,
  ShoppingCart,
  Box,
  DollarSign,
  List,
  ChartBar,
  LucideIcon,
  Building2,
  GitBranch,
  CheckSquare,
  Shield,
} from "lucide-react";

export const getAccordionIcon = (label: string): LucideIcon => {
  const iconMap: Record<string, LucideIcon> = {
    "Admin Console": Shield,
    Dashboard: LayoutDashboard,
    "Nadi Dashboard": LayoutDashboard,
    "IoT Dashboard": LayoutDashboard,
    "Site Management": Building2,
    "Member Management": Users,
    "POS Management": ShoppingCart,
    "Asset Management": Box,
    "Inventory Management": Box,
    "Maintainance Management": Box,
    "Human Resource Management": Users,
    "Finance Management": DollarSign,
    "Financial Management": DollarSign,
    "Programmes Management": List,
    "Claim Management": FileCheck,
    Reports: ChartBar,
    Community: MessageSquare,
    Compliance: FileCheck,
    "Workflow Management": GitBranch,
    "Service Module": Settings,
    "Report Management": ChartBar,
    Announcements: CheckSquare,
  };
  return iconMap[label] || LayoutDashboard;
};
